### ISSUE TITLE
VideoPlayer not playing for Quest

### ISSUE THREAD

**Issue by hackthedev** [MerlinVR/USharpVideo#24]
Do I need to enable some setting so that the Quest Platform can use this Video Player as well?

USharpVideo:
https://shy-devils.life-is-pa.in/539OhVBPt

VideoScreen:
https://shy-devils.life-is-pa.in/539OpnhgA

Internals: 
https://shy-devils.life-is-pa.in/539OrMf9T

**Comment by MerlinVR** [comment]
Quest cannot resolve links to videos, that is a fundamental limitation of VRC on Quest at the moment. This means you need to give it a direct link to the .mp4 of the video. You can host videos on a CDN which allows that. I personally use BunnyCDN, but there are many CDNs to choose from. Though I wouldn't recommend a free CDN since they are generally very flaky. You can also use Vimeo with Vimeo Pro to get direct links to your uploaded videos with the benefit of it not being blocked by the trusted URL list, though it can be more expensive than a CDN depending on how much traffic your world gets.

**Comment by hackthedev** [comment]
Okay I see. Well thats sad. Maybe it will get updated in the feature to do so.
Thank you very much. I love your quick reaction time

**Comment by hackthedev** [comment]
Okay so i fixed the issue by downloading all my videos and uploading them to my web server, then setting the source url from my web server in both pc and quest version.

Now my question:
If is it to shuffle the playlist, will the shuffle be synced?

**Comment by MerlinVR** [comment]
Yes the shuffle playlist option is synced.
