### ISSUE TITLE
Video error/retrying loop in latest VRC open beta

### ISSUE THREAD

**Issue by towneh** [MerlinVR/USharpVideo#25]
VRChat 2021.3.1, build 1112.

SDK3 world version 2021.06.03.14.57 (latest release version)

World used https://vrch.at/wrld_515214e6-c364-4206-bd8b-e1023ffa6408

USharpVideo script configured with default stream mode and low latency enabled, default playlist https://www.youtube.com/watch?v=YSBO7Zl8mU4 which is a youtube stream.

You can see the behaviour here, no manual intervention was made, it eventually stopped looping after a time: https://cdn.discordapp.com/attachments/756114559991021600/863391536723787776/2021-07-10_13-04-48.mp4

If I stop the player and then press play again, or put in another youtube stream link, it will also exhibit the same behaviour. So it's not specifically tied to coming in to the world.

Testing other video types: youtube videos in video mode, twitch streams in stream mode, vrcdn streams in stream mode, do NOT show this issue. It seems specific to just youtube streams so far.

**Comment by MerlinVR** [comment]
I am unable to reproduce this in your linked world on open beta with the world's default stream or another YouTube stream, can you attach an output log?

**Comment by towneh** [comment]
[VRCLogs.txt](https://github.com/MerlinVR/USharpVideo/files/6796086/VRCLogs.txt)

**Comment by MerlinVR** [comment]
It looks like it's just failing to play the format. There is nothing USharpVideo can do about that, the retries are the best it can do and it's repeatedly failing for you. 

If you can get other people to confirm that it is broken on open beta and not on live, I'd advise you to make a canny about avpro having issues with the stream. But I would encourage you to test it thoroughly before making a canny since youtube can often serve streams in the incorrect format intermittently even on live. Since it works for me I feel like that's what's likely happening.

**Comment by towneh** [comment]
I tested again tonight and can confirm I can't reproduce the issue so I agree this is likely an avpro/youtube issue, thanks!
